# Generated by Django 5.2.17 on 2026-09-21 19:34

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use lowercase letters, digits, and hyphens.",
                                regex="^[a-z0-9][a-z0-9-]*$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="LandingCopyRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("copy", models.JSONField()),
                ("change_summary", models.CharField(max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_landing_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        max_length=80,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use lowercase letters, digits, and hyphens.",
                                regex="^[a-z0-9][a-z0-9-]*$",
                            )
                        ],
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use a locale such as es-CO or en-US.",
                                regex="^[a-z]{2}-[A-Z]{2}$",
                            )
                        ],
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_landing_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="landing_copy.landingcopyrevision",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="landing_copy.site",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="landingcopyrevision",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="landing_copy.landingpage",
            ),
        ),
        migrations.AddConstraint(
            model_name="landingcopyrevision",
            constraint=models.UniqueConstraint(
                fields=("page", "version"), name="unique_landing_copy_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="landingcopyrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="landing_copy_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="landingpage",
            constraint=models.UniqueConstraint(
                fields=("site", "slug", "locale"), name="unique_landing_page_locale"
            ),
        ),
    ]
